name: Windows Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3.5.0
      with:
        java-version: 17
        distribution: temurin
          
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
        
    - name: Run build with Gradle wrapper
      run: ./gradlew packageExe
      
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: windows-binary
        path: build/compose/binaries/main/exe/main-1.0.0.exe
